---
- name: Install Epel
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install Redis
  package:
    name: redis
    state: present

- name: Enable Redis
  service:
    name: redis
    state: started
    enabled: yes

- name: Inject bind address into /etc/redis.conf
  lineinfile:
    dest: /etc/redis.conf
    regexp: "^bind "
    line: "bind {{ bind_address }}"

- name: Restart Redis
  service:
    name: redis
    state: restarted
    enabled: yes
