---
- name: Ensure packages are up to date
  package:
    update_cache: yes

- name: Install Epel
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when:
    ansible_distribution == "RedHat" and ansible_distribution_major_version == "7" or
    ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" or
    ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
