---
- name: Gather RedHat based systems' specific variables
  include_vars: "redhat.yaml"
  when:
    ansible_distribution == "RedHat" or
    ansible_distribution == "CentOS" or
    ansible_distribution == "Amazon"

- name: Gather Debian based systems' specific variables
  include_vars: "debian.yaml"
  when:
    ansible_distribution == "Debian" or
    ansible_distribution == "Ubuntu"

- name: Install tyk-gateway required packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ required_packages }}"

- name: Add tyk-gateway public key to verify package
  apt_key:
    url: https://packagecloud.io/tyk/tyk-gateway/gpgkey
    state: present
  when:
    ansible_distribution == "Ubuntu" or
    ansible_distribution == "Debian"

- name: "Copy {{ package_def_file }}"
  template:
    src: "../files/{{ package_def_file }}"
    dest: "{{ package_def_folder }}/{{ package_def_file }}"

- name: Inject Tyk environment varibales into /etc/sysconfig/tyk-gateway
  include_tasks: configure.yaml

- name: Install tyk-gateway
  package:
    name: tyk-gateway
    state: present
    update_cache: yes

- name: Check if Python 3.7 is installed
  stat:
    path: /usr/local/bin/python3.7
  register: py

- name: Include Python 3.7 installation task
  include_tasks: python3.yaml
  when:
    ansible_distribution == "RedHat" and ansible_distribution_major_version == "8" and not py.stat.exists
