---
- name: Install python3 dependencies
  dnf:
    name:
      - gcc
      - openssl-devel
      - bzip2-devel
      - libffi-devel
    state: latest

- name: Install make dependency
  dnf:
    name: make
    state: latest

- name: Create /opt/tyk-gateway/tmp directory
  file:
    path: /opt/tyk-gateway/tmp/
    state: directory

- name: Download Python-3.7.9.tgz
  get_url:
    url: https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
    dest: /opt/tyk-gateway/tmp/Python-3.7.9.tgz

- name: Extract Python-3.7.9.tgz into /opt/tyk-gateway/tmp/Python-3.7.9/
  shell: sudo tar xzf /opt/tyk-gateway/tmp/Python-3.7.9.tgz  --directory /opt/tyk-gateway/tmp/

- name: Configure Python 3.7.9 with  --enable-shared --enable-optimizations --prefix=/usr flags
  shell: sudo /opt/tyk-gateway/tmp/Python-3.7.9/configure --enable-shared --enable-optimizations --prefix=/usr

- name: Use make command to complete Python 3.7.9 installation
  shell: sudo make install

- name: Load Python library config from /usr/lib
  shell: sudo ldconfig /usr/lib

- name: Remove /opt/tyk-gateway/tmp directory
  file:
    path: /opt/tyk-gateway/tmp/
    state: absent

- name: Install protobuf for Python 3.7
  pip:
    name: protobuf
    executable: /usr/bin/pip3.7

- name: Install grpcio for Python 3.7
  pip:
    name: grpcio
    executable: /usr/bin/pip3.7 