---
- name: Copy mongodb-org-4.4.repo
  copy:
    src: ../files/mongodb-org-4.4.repo
    dest: /etc/yum.repos.d/mongodb-org-4.4.repo

- name: Install MongoDB
  package:
    name: mongodb-org
    state: present

- name: Enable MongoDB
  service:
    name: mongod
    state: started
    enabled: yes

- name: Inject bind address into /etc/mongod.conf
  lineinfile:
    dest: /etc/mongod.conf
    regexp: "^  bindIp: "
    line: "  bindIp: {{ bind_address }}"

- name: Restart Redis
  service:
    name: mongod
    state: restarted
    enabled: yes
