---
- hosts: redis
  become: true
  vars_files:
  - ./vars/redis.yaml

  roles:
    - redis
    - geerlingguy.redis

  tags:
    - redis

- hosts: mongodb
  become: true
  vars_files:
  - ./vars/mongodb.yaml

  roles:
    - community.mongodb.mongodb_repository
    - mongodb
    - community.mongodb.mongodb_install
    - community.mongodb.mongodb_mongod

  tags:
    - mongodb

- hosts: dashboard
  become: true
  vars_files:
  - ./vars/tyk.yaml

  roles:
    - dashboard

  tags:
    - tyk-dashboard
    - tyk-pro

- hosts: gateway
  become: true
  vars_files:
    - ./vars/tyk.yaml

  roles:
    - gateway

  tags:
    - tyk-gateway
    - tyk-pro
    - tyk-ce

- hosts: pump
  become: true
  vars_files:
    - ./vars/tyk.yaml

  roles:
    - pump

  tags:
    - tyk-pump
    - tyk-pro
