---
- hosts: redis
  become: true
  vars_files:
    - ./vars/redis.yml

  roles:
    - redis
    - geerlingguy.redis

  tags:
    - redis

- hosts: mongodb
  become: true
  vars_files:
    - ./vars/mongodb.yml

  roles:
    - community.mongodb.mongodb_repository
    - mongodb
    - community.mongodb.mongodb_install
    - community.mongodb.mongodb_mongod

  tags:
    - mongodb

- hosts: pgsql
  become: true
  vars_files:
    - ./vars/pgsql.yml

  roles:
    - geerlingguy.postgresql

  tags:
    - pgsql

- hosts: dashboard
  become: true
  vars_files:
    - ./vars/tyk.yml
    - ./vars/pgsql.yml

  roles:
    - dashboard

  tags:
    - tyk-pro

- hosts: gateway
  become: true
  vars_files:
    - ./vars/tyk.yml

  roles:
    - gateway

  tags:
    - tyk-pro
    - tyk-gateway-ce
    - tyk-gateway-pro
    - tyk-gateway-hybrid

- hosts: pump
  become: true
  vars_files:
    - ./vars/tyk.yml
    - ./vars/pgsql.yml

  roles:
    - pump

  tags:
    - tyk-pro
    - tyk-pump
